export const launchers = [
  {
    id: "c39809ff-fb6e-4218-b869-a43a2b3d3518",
    url: "https://ll.thespacedevs.com/2.2.0/launch/c39809ff-fb6e-4218-b869-a43a2b3d3518/",
    slug: "long-march-2cyz-1s-unknown",
    name: "Long March 2C/YZ-1S (?) | Unknown",
    status: {
      id: 1,
      name: "Go for Launch",
      abbrev: "Go",
      description: "Current T-0 confirmed by official or reliable sources.",
    },
    last_updated: "2021-11-18T08:14:18Z",
    net: "2021-11-22T23:50:00Z",
    window_end: "2021-11-23T00:04:00Z",
    window_start: "2021-11-22T23:37:00Z",
    probability: null,
    holdreason: "",
    failreason: "",
    hashtag: null,
    launch_service_provider: {
      id: 88,
      url: "https://ll.thespacedevs.com/2.2.0/agencies/88/",
      name: "China Aerospace Science and Technology Corporation",
      type: "Government",
    },
    rocket: {
      id: 2714,
      configuration: {
        id: 156,
        url: "https://ll.thespacedevs.com/2.2.0/config/launcher/156/",
        name: "Long March 2C/YZ-1S",
        family: "Long March 2",
        full_name: "Long March 2C/YZ-1S",
        variant: "C/YZ-1S",
      },
    },
    mission: null,
    pad: {
      id: 22,
      url: "https://ll.thespacedevs.com/2.2.0/pad/22/",
      agency_id: null,
      name: "Launch Area 4 (SLS-2 / 603)",
      info_url: null,
      wiki_url: "https://en.wikipedia.org/wiki/Jiuquan_Launch_Area_4",
      map_url: "http://maps.google.com/maps?q=40.960556,100.298333",
      latitude: "40.960556",
      longitude: "100.298333",
      location: {
        id: 17,
        url: "https://ll.thespacedevs.com/2.2.0/location/17/",
        name: "Jiuquan, People's Republic of China",
        country_code: "CHN",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_17_20200803142429.jpg",
        total_launch_count: 150,
        total_landing_count: 0,
      },
      map_image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_22_20200803143437.jpg",
      total_launch_count: 73,
    },
    webcast_live: false,
    image:
      "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/long_march_2c__image_20210908193511.jpeg",
    infographic: null,
    program: [],
  },
  {
    id: "c4b2f90e-3385-4cbe-a89f-fc5f57da1bfb",
    url: "https://ll.thespacedevs.com/2.2.0/launch/c4b2f90e-3385-4cbe-a89f-fc5f57da1bfb/",
    slug: "falcon-9-block-5-double-asteroid-redirection-test",
    name: "Falcon 9 Block 5 | Double Asteroid Redirection Test (DART)",
    status: {
      id: 1,
      name: "Go for Launch",
      abbrev: "Go",
      description: "Current T-0 confirmed by official or reliable sources.",
    },
    last_updated: "2021-11-21T18:59:03Z",
    net: "2021-11-24T06:21:00Z",
    window_end: "2021-11-24T06:21:00Z",
    window_start: "2021-11-24T06:21:00Z",
    probability: -1,
    holdreason: "",
    failreason: "",
    hashtag: null,
    launch_service_provider: {
      id: 121,
      url: "https://ll.thespacedevs.com/2.2.0/agencies/121/",
      name: "SpaceX",
      type: "Commercial",
    },
    rocket: {
      id: 2419,
      configuration: {
        id: 164,
        url: "https://ll.thespacedevs.com/2.2.0/config/launcher/164/",
        name: "Falcon 9",
        family: "Falcon",
        full_name: "Falcon 9 Block 5",
        variant: "Block 5",
      },
    },
    mission: {
      id: 986,
      name: "Double Asteroid Redirection Test (DART)",
      description:
        "Double Asteroid Redirection Test (DART) mission is the first-ever mission to demonstrate the capability to deflect an asteroid by colliding a spacecraft with it at high speed, a technique known as a kinetic impactor.\r\n\r\nDART is a planetary defense-driven test of one of the technologies for preventing the Earth impact of a hazardous asteroid: the kinetic impactor.  DART's primary objective is to demonstrate a kinetic impact on a small asteroid.  The binary near-Earth asteroid (65803) Didymos is the target for DART.   While Didymos' primary body is approximately 800 meters across, its secondary body has a 150-meter size, which is more typical of the size of asteroids that could pose a more common hazard to Earth.\r\n\r\nThe DART spacecraft will achieve the kinetic impact by deliberately crashing itself into the moonlet at a speed of approximately 6 km/s, with the aid of an onboard camera and sophisticated autonomous navigation software. The collision will change the speed of the moonlet in its orbit around the main body by a fraction of one percent, enough to be measured using telescopes on Earth.",
      launch_designator: null,
      type: "Robotic Exploration",
      orbit: {
        id: 6,
        name: "Heliocentric N/A",
        abbrev: "Helio-N/A",
      },
    },
    pad: {
      id: 16,
      url: "https://ll.thespacedevs.com/2.2.0/pad/16/",
      agency_id: null,
      name: "Space Launch Complex 4E",
      info_url: null,
      wiki_url: "",
      map_url: "http://maps.google.com/maps?q=34.632+N,+120.611+W",
      latitude: "34.632",
      longitude: "-120.611",
      location: {
        id: 11,
        url: "https://ll.thespacedevs.com/2.2.0/location/11/",
        name: "Vandenberg SFB, CA, USA",
        country_code: "USA",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_11_20200803142416.jpg",
        total_launch_count: 691,
        total_landing_count: 3,
      },
      map_image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_16_20200803143532.jpg",
      total_launch_count: 85,
    },
    webcast_live: false,
    image:
      "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/falcon_9_block__image_20210506060831.jpg",
    infographic: null,
    program: [],
  },
  {
    id: "89ee335d-53bd-49e0-a774-921321f5926f",
    url: "https://ll.thespacedevs.com/2.2.0/launch/89ee335d-53bd-49e0-a774-921321f5926f/",
    slug: "soyuz-21b-uzlovoy-module-um-prichal",
    name: 'Soyuz 2.1b | Uzlovoy Module (UM) "Prichal"',
    status: {
      id: 1,
      name: "Go for Launch",
      abbrev: "Go",
      description: "Current T-0 confirmed by official or reliable sources.",
    },
    last_updated: "2021-11-20T10:57:34Z",
    net: "2021-11-24T13:06:36Z",
    window_end: "2021-11-24T13:06:36Z",
    window_start: "2021-11-24T13:06:36Z",
    probability: -1,
    holdreason: "",
    failreason: "",
    hashtag: null,
    launch_service_provider: {
      id: 63,
      url: "https://ll.thespacedevs.com/2.2.0/agencies/63/",
      name: "Russian Federal Space Agency (ROSCOSMOS)",
      type: "Government",
    },
    rocket: {
      id: 149,
      configuration: {
        id: 15,
        url: "https://ll.thespacedevs.com/2.2.0/config/launcher/15/",
        name: "Soyuz 2.1b",
        family: "Soyuz",
        full_name: "Soyuz 2.1b",
        variant: "",
      },
    },
    mission: {
      id: 669,
      name: 'Uzlovoy Module (UM) "Prichal"',
      description:
        "The UM (Uzlovoy Module) or NM (Node Module) is a node to be added to the Russian part of the ISS complex. It is also named Prichal.\n\nUM will be delivered by a modified Progress space tug, called Progress-M-UM. The UM will be docked to the nadir port of the MLM (Nauka) module, providing four ports to mount additional modules and one docking port for cargo and crew spacecrafts.",
      launch_designator: null,
      type: "Human Exploration",
      orbit: {
        id: 8,
        name: "Low Earth Orbit",
        abbrev: "LEO",
      },
    },
    pad: {
      id: 20,
      url: "https://ll.thespacedevs.com/2.2.0/pad/20/",
      agency_id: null,
      name: "31/6",
      info_url: null,
      wiki_url: "",
      map_url: "http://maps.google.com/maps?q=45.996+N,+63.564+E",
      latitude: "45.996034",
      longitude: "63.564003",
      location: {
        id: 15,
        url: "https://ll.thespacedevs.com/2.2.0/location/15/",
        name: "Baikonur Cosmodrome, Republic of Kazakhstan",
        country_code: "KAZ",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_15_20200803142517.jpg",
        total_launch_count: 1525,
        total_landing_count: 0,
      },
      map_image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_20_20200803143516.jpg",
      total_launch_count: 396,
    },
    webcast_live: false,
    image:
      "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/soyuz_2.1b_image_20200513182641.jpg",
    infographic: null,
    program: [
      {
        id: 17,
        url: "https://ll.thespacedevs.com/2.2.0/program/17/",
        name: "International Space Station",
        description:
          "The International Space Station programme is tied together by a complex set of legal, political and financial agreements between the sixteen nations involved in the project, governing ownership of the various components, rights to crewing and utilization, and responsibilities for crew rotation and resupply of the International Space Station. It was conceived in 1984 by President Ronald Reagan, during the Space Station Freedom project as it was originally called.",
        agencies: [
          {
            id: 16,
            url: "https://ll.thespacedevs.com/2.2.0/agencies/16/",
            name: "Canadian Space Agency",
            type: "Government",
          },
          {
            id: 27,
            url: "https://ll.thespacedevs.com/2.2.0/agencies/27/",
            name: "European Space Agency",
            type: "Multinational",
          },
          {
            id: 37,
            url: "https://ll.thespacedevs.com/2.2.0/agencies/37/",
            name: "Japan Aerospace Exploration Agency",
            type: "Government",
          },
          {
            id: 44,
            url: "https://ll.thespacedevs.com/2.2.0/agencies/44/",
            name: "National Aeronautics and Space Administration",
            type: "Government",
          },
          {
            id: 63,
            url: "https://ll.thespacedevs.com/2.2.0/agencies/63/",
            name: "Russian Federal Space Agency (ROSCOSMOS)",
            type: "Government",
          },
        ],
        image_url:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/program_images/international2_program_20201129184745.png",
        start_date: "1998-11-20T06:40:00Z",
        end_date: null,
        info_url: "https://www.nasa.gov/mission_pages/station/main/index.html",
        wiki_url:
          "https://en.wikipedia.org/wiki/International_Space_Station_programme",
        mission_patches: [],
      },
    ],
  },
  {
    id: "6aa3fa12-04a7-4e87-9058-5aa24efb91aa",
    url: "https://ll.thespacedevs.com/2.2.0/launch/6aa3fa12-04a7-4e87-9058-5aa24efb91aa/",
    slug: "long-march-3b-chinasat-6d",
    name: "Long March 3B (?) | ChinaSat 6D (?)",
    status: {
      id: 1,
      name: "Go for Launch",
      abbrev: "Go",
      description: "Current T-0 confirmed by official or reliable sources.",
    },
    last_updated: "2021-11-18T08:14:23Z",
    net: "2021-11-24T16:15:00Z",
    window_end: "2021-11-24T19:00:00Z",
    window_start: "2021-11-24T16:00:00Z",
    probability: null,
    holdreason: "",
    failreason: "",
    hashtag: null,
    launch_service_provider: {
      id: 88,
      url: "https://ll.thespacedevs.com/2.2.0/agencies/88/",
      name: "China Aerospace Science and Technology Corporation",
      type: "Government",
    },
    rocket: {
      id: 2753,
      configuration: {
        id: 50,
        url: "https://ll.thespacedevs.com/2.2.0/config/launcher/50/",
        name: "Long March 3",
        family: "Long March 3",
        full_name: "Long March 3B/E",
        variant: "B/E",
      },
    },
    mission: null,
    pad: {
      id: 45,
      url: "https://ll.thespacedevs.com/2.2.0/pad/45/",
      agency_id: null,
      name: "Launch Complex 2 (LC-2)",
      info_url: null,
      wiki_url: "https://en.wikipedia.org/wiki/Xichang_Satellite_Launch_Center",
      map_url: "https://www.google.com/maps/?q=28.246017,102.026556",
      latitude: "28.246017",
      longitude: "102.026556",
      location: {
        id: 16,
        url: "https://ll.thespacedevs.com/2.2.0/location/16/",
        name: "Xichang Satellite Launch Center, People's Republic of China",
        country_code: "CHN",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_16_20200803142513.jpg",
        total_launch_count: 164,
        total_landing_count: 0,
      },
      map_image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_45_20200803143520.jpg",
      total_launch_count: 86,
    },
    webcast_live: false,
    image:
      "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/long2520march25203_image_20190224025008.jpeg",
    infographic: null,
    program: [],
  },
  {
    id: "12ed3429-fab7-4bc7-8d03-aa4dbe5f6228",
    url: "https://ll.thespacedevs.com/2.2.0/launch/12ed3429-fab7-4bc7-8d03-aa4dbe5f6228/",
    slug: "soyuz-21bfregat-eks-5-tundra-5",
    name: "Soyuz 2.1b/Fregat | EKS 5 (Tundra 5)",
    status: {
      id: 1,
      name: "Go for Launch",
      abbrev: "Go",
      description: "Current T-0 confirmed by official or reliable sources.",
    },
    last_updated: "2021-11-19T18:51:38Z",
    net: "2021-11-25T01:09:13Z",
    window_end: "2021-11-25T02:30:00Z",
    window_start: "2021-11-25T00:30:00Z",
    probability: null,
    holdreason: "",
    failreason: "",
    hashtag: null,
    launch_service_provider: {
      id: 193,
      url: "https://ll.thespacedevs.com/2.2.0/agencies/193/",
      name: "Russian Space Forces",
      type: "Government",
    },
    rocket: {
      id: 7492,
      configuration: {
        id: 42,
        url: "https://ll.thespacedevs.com/2.2.0/config/launcher/42/",
        name: "Soyuz 2.1b/Fregat",
        family: "Soyuz",
        full_name: "Soyuz 2.1b Fregat",
        variant: "Fregat",
      },
    },
    mission: {
      id: 5887,
      name: "EKS 5 (Tundra 5)",
      description:
        "The Tundra or EKS (meaning Unified Space System) series of satellites is the next generation of Russian early warning satellites.",
      launch_designator: null,
      type: "Government/Top Secret",
      orbit: {
        id: 0,
        name: "Elliptical Orbit",
        abbrev: "Elliptical",
      },
    },
    pad: {
      id: 85,
      url: "https://ll.thespacedevs.com/2.2.0/pad/85/",
      agency_id: 163,
      name: "43/4 (43R)",
      info_url: null,
      wiki_url: "",
      map_url: "http://maps.google.com/maps?q=62.929+N,+40.457+E",
      latitude: "62.92883",
      longitude: "40.457098",
      location: {
        id: 6,
        url: "https://ll.thespacedevs.com/2.2.0/location/6/",
        name: "Plesetsk Cosmodrome, Russian Federation",
        country_code: "RUS",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_6_20200803142434.jpg",
        total_launch_count: 1644,
        total_landing_count: 0,
      },
      map_image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_85_20200803143554.jpg",
      total_launch_count: 303,
    },
    webcast_live: false,
    image:
      "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/soyuz25202.1b_image_20190520165608.png",
    infographic: null,
    program: [],
  },
  {
    id: "029615cc-ef67-4a1e-b98e-08bdbfb3ae7e",
    url: "https://ll.thespacedevs.com/2.2.0/launch/029615cc-ef67-4a1e-b98e-08bdbfb3ae7e/",
    slug: "electron-a-data-with-destiny",
    name: "Electron | A Data With Destiny",
    status: {
      id: 8,
      name: "To Be Confirmed",
      abbrev: "TBC",
      description:
        "Awaiting official confirmation - current date is known with some certainty.",
    },
    last_updated: "2021-10-11T10:54:34Z",
    net: "2021-11-27T00:00:00Z",
    window_end: "2021-11-27T00:00:00Z",
    window_start: "2021-11-27T00:00:00Z",
    probability: null,
    holdreason: "",
    failreason: "",
    hashtag: null,
    launch_service_provider: {
      id: 147,
      url: "https://ll.thespacedevs.com/2.2.0/agencies/147/",
      name: "Rocket Lab Ltd",
      type: "Commercial",
    },
    rocket: {
      id: 7474,
      configuration: {
        id: 26,
        url: "https://ll.thespacedevs.com/2.2.0/config/launcher/26/",
        name: "Electron",
        family: "Electron",
        full_name: "Electron",
        variant: "",
      },
    },
    mission: {
      id: 5874,
      name: "A Data With Destiny",
      description:
        "Payload consists of two BlackSky Gen-2 high-resolution multi-spectral Earth observation satellites.",
      launch_designator: null,
      type: "Earth Science",
      orbit: {
        id: 17,
        name: "Sun-Synchronous Orbit",
        abbrev: "SSO",
      },
    },
    pad: {
      id: 65,
      url: "https://ll.thespacedevs.com/2.2.0/pad/65/",
      agency_id: 147,
      name: "Rocket Lab Launch Complex 1A",
      info_url: null,
      wiki_url: "https://en.wikipedia.org/wiki/Rocket_Lab_Launch_Complex_1",
      map_url: "https://www.google.com/maps/place/-39.262833,177.864469",
      latitude: "-39.262833",
      longitude: "177.864469",
      location: {
        id: 10,
        url: "https://ll.thespacedevs.com/2.2.0/location/10/",
        name: "Onenui Station, Mahia Peninsula, New Zealand",
        country_code: "NZL",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_10_20200803142509.jpg",
        total_launch_count: 22,
        total_landing_count: 3,
      },
      map_image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_65_20200803143549.jpg",
      total_launch_count: 22,
    },
    webcast_live: false,
    image:
      "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/electron_image_20190705175640.jpeg",
    infographic: null,
    program: [],
  },
  {
    id: "56db9abd-41b8-41a3-9d6d-88e52460682b",
    url: "https://ll.thespacedevs.com/2.2.0/launch/56db9abd-41b8-41a3-9d6d-88e52460682b/",
    slug: "falcon-9-block-5-starlink-4-3",
    name: "Falcon 9 Block 5 | Starlink 4-3",
    status: {
      id: 8,
      name: "To Be Confirmed",
      abbrev: "TBC",
      description:
        "Awaiting official confirmation - current date is known with some certainty.",
    },
    last_updated: "2021-11-20T22:13:48Z",
    net: "2021-12-01T23:20:00Z",
    window_end: "2021-12-01T23:20:00Z",
    window_start: "2021-12-01T23:20:00Z",
    probability: null,
    holdreason: "",
    failreason: "",
    hashtag: null,
    launch_service_provider: {
      id: 121,
      url: "https://ll.thespacedevs.com/2.2.0/agencies/121/",
      name: "SpaceX",
      type: "Commercial",
    },
    rocket: {
      id: 7494,
      configuration: {
        id: 164,
        url: "https://ll.thespacedevs.com/2.2.0/config/launcher/164/",
        name: "Falcon 9",
        family: "Falcon",
        full_name: "Falcon 9 Block 5",
        variant: "Block 5",
      },
    },
    mission: {
      id: 5886,
      name: "Starlink 4-3",
      description:
        "A batch of 53 satellites for Starlink mega-constellation - SpaceX's project for space-based Internet communication system.",
      launch_designator: null,
      type: "Communications",
      orbit: {
        id: 8,
        name: "Low Earth Orbit",
        abbrev: "LEO",
      },
    },
    pad: {
      id: 80,
      url: "https://ll.thespacedevs.com/2.2.0/pad/80/",
      agency_id: 121,
      name: "Space Launch Complex 40",
      info_url: null,
      wiki_url:
        "https://en.wikipedia.org/wiki/Cape_Canaveral_Air_Force_Station_Space_Launch_Complex_40",
      map_url: "http://maps.google.com/maps?q=28.56194122,-80.57735736",
      latitude: "28.56194122",
      longitude: "-80.57735736",
      location: {
        id: 12,
        url: "https://ll.thespacedevs.com/2.2.0/location/12/",
        name: "Cape Canaveral, FL, USA",
        country_code: "USA",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_12_20200803142519.jpg",
        total_launch_count: 827,
        total_landing_count: 21,
      },
      map_image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_80_20200803143323.jpg",
      total_launch_count: 131,
    },
    webcast_live: false,
    image:
      "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/falcon2520925_image_20211117170531.png",
    infographic: null,
    program: [],
  },
  {
    id: "8464fae8-48ef-4e35-860c-07347f339ce2",
    url: "https://ll.thespacedevs.com/2.2.0/launch/8464fae8-48ef-4e35-860c-07347f339ce2/",
    slug: "soyuz-stbfregat-2-x-galileo",
    name: "Soyuz STB/Fregat | 2 x Galileo",
    status: {
      id: 1,
      name: "Go for Launch",
      abbrev: "Go",
      description: "Current T-0 confirmed by official or reliable sources.",
    },
    last_updated: "2021-11-18T17:34:45Z",
    net: "2021-12-02T00:31:00Z",
    window_end: "2021-12-02T00:31:00Z",
    window_start: "2021-12-02T00:31:00Z",
    probability: -1,
    holdreason: "",
    failreason: "",
    hashtag: null,
    launch_service_provider: {
      id: 115,
      url: "https://ll.thespacedevs.com/2.2.0/agencies/115/",
      name: "Arianespace",
      type: "Commercial",
    },
    rocket: {
      id: 2701,
      configuration: {
        id: 171,
        url: "https://ll.thespacedevs.com/2.2.0/config/launcher/171/",
        name: "Soyuz STB",
        family: "Soyuz",
        full_name: "Soyuz STB Fregat",
        variant: "STB/Fregat",
      },
    },
    mission: {
      id: 5846,
      name: "2 x Galileo",
      description:
        "Payload consists of two satellites for Europe's Galileo navigation system.",
      launch_designator: null,
      type: "Navigation",
      orbit: {
        id: 12,
        name: "Medium Earth Orbit",
        abbrev: "MEO",
      },
    },
    pad: {
      id: 81,
      url: "https://ll.thespacedevs.com/2.2.0/pad/81/",
      agency_id: 115,
      name: "Soyuz Launch Complex",
      info_url: null,
      wiki_url: "https://en.wikipedia.org/wiki/Ensemble_de_Lancement_Soyouz",
      map_url: "https://www.google.com/maps/?q=5.3019,-52.8346",
      latitude: "5.3019",
      longitude: "-52.8346",
      location: {
        id: 13,
        url: "https://ll.thespacedevs.com/2.2.0/location/13/",
        name: "Kourou, French Guiana",
        country_code: "GUF",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_13_20200803142412.jpg",
        total_launch_count: 309,
        total_landing_count: 0,
      },
      map_image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_81_20200803143601.jpg",
      total_launch_count: 24,
    },
    webcast_live: false,
    image:
      "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/soyuz2520stb_image_20190224025011.jpeg",
    infographic: null,
    program: [],
  },
  {
    id: "0914dabd-ac92-444b-bf9f-7a6b08bb06e1",
    url: "https://ll.thespacedevs.com/2.2.0/launch/0914dabd-ac92-444b-bf9f-7a6b08bb06e1/",
    slug: "launcherone-ignis-others",
    name: "LauncherOne | Ignis & others",
    status: {
      id: 8,
      name: "To Be Confirmed",
      abbrev: "TBC",
      description:
        "Awaiting official confirmation - current date is known with some certainty.",
    },
    last_updated: "2021-11-11T03:18:48Z",
    net: "2021-12-02T18:00:00Z",
    window_end: "2021-12-02T22:00:00Z",
    window_start: "2021-12-02T18:00:00Z",
    probability: -1,
    holdreason: "",
    failreason: "",
    hashtag: null,
    launch_service_provider: {
      id: 199,
      url: "https://ll.thespacedevs.com/2.2.0/agencies/199/",
      name: "Virgin Orbit",
      type: "Commercial",
    },
    rocket: {
      id: 2464,
      configuration: {
        id: 141,
        url: "https://ll.thespacedevs.com/2.2.0/config/launcher/141/",
        name: "LauncherOne",
        family: "Launcher",
        full_name: "LauncherOne",
        variant: "One",
      },
    },
    mission: {
      id: 5884,
      name: "Above the Clouds",
      description:
        "Mission to a 500 km circular orbit inclined at 45 degrees carrying eight R&D satellites from US government agencies with communications and navigation experiments as well as two Earth-observation nanosatellites from Polish company SatRevolution.",
      launch_designator: null,
      type: "Communications",
      orbit: {
        id: 8,
        name: "Low Earth Orbit",
        abbrev: "LEO",
      },
    },
    pad: {
      id: 53,
      url: "https://ll.thespacedevs.com/2.2.0/pad/53/",
      agency_id: null,
      name: "Mojave Air and Space Port",
      info_url: null,
      wiki_url: "https://en.wikipedia.org/wiki/Mojave_Air_and_Space_Port",
      map_url:
        "https://www.google.com/maps/place/35Â°03'34.0\"N+118Â°09'06.0\"W/",
      latitude: "35.059444",
      longitude: "-118.151667",
      location: {
        id: 20,
        url: "https://ll.thespacedevs.com/2.2.0/location/20/",
        name: "Air launch to orbit",
        country_code: "UNK",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_20_20200803142433.jpg",
        total_launch_count: 49,
        total_landing_count: 0,
      },
      map_image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_53_20200803143612.jpg",
      total_launch_count: 3,
    },
    webcast_live: false,
    image:
      "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/launcherone_image_20200101110016.jpeg",
    infographic: null,
    program: [],
  },
  {
    id: "495fe114-753d-48b1-9d23-eb9adaa3fb23",
    url: "https://ll.thespacedevs.com/2.2.0/launch/495fe114-753d-48b1-9d23-eb9adaa3fb23/",
    slug: "atlas-v-551-stp-3",
    name: "Atlas V 551 | STP-3",
    status: {
      id: 8,
      name: "To Be Confirmed",
      abbrev: "TBC",
      description:
        "Awaiting official confirmation - current date is known with some certainty.",
    },
    last_updated: "2021-11-11T09:51:52Z",
    net: "2021-12-04T09:04:00Z",
    window_end: "2021-12-04T11:04:00Z",
    window_start: "2021-12-04T09:04:00Z",
    probability: -1,
    holdreason: "",
    failreason: "",
    hashtag: null,
    launch_service_provider: {
      id: 124,
      url: "https://ll.thespacedevs.com/2.2.0/agencies/124/",
      name: "United Launch Alliance",
      type: "Commercial",
    },
    rocket: {
      id: 111,
      configuration: {
        id: 27,
        url: "https://ll.thespacedevs.com/2.2.0/config/launcher/27/",
        name: "Atlas V 551",
        family: "Atlas",
        full_name: "Atlas V 551",
        variant: "551",
      },
    },
    mission: {
      id: 1371,
      name: "STP-3",
      description:
        "Rideshare mission with the STPSat-6 satellite and six secondary payloads for the US Air Force. STPSat-6 carries the NNSA's Space and Atmospheric Burst Reporting System-3 (SABRS-3) payload and NASA's Laser Communications Relay Demonstration (LCRD) experiment.",
      launch_designator: null,
      type: "Dedicated Rideshare",
      orbit: {
        id: 1,
        name: "Geostationary Orbit",
        abbrev: "Direct-GEO",
      },
    },
    pad: {
      id: 29,
      url: "https://ll.thespacedevs.com/2.2.0/pad/29/",
      agency_id: null,
      name: "Space Launch Complex 41",
      info_url: null,
      wiki_url:
        "https://en.wikipedia.org/wiki/Cape_Canaveral_Air_Force_Station_Space_Launch_Complex_41",
      map_url: "http://maps.google.com/maps?q=28.58341025,-80.58303644",
      latitude: "28.58341025",
      longitude: "-80.58303644",
      location: {
        id: 12,
        url: "https://ll.thespacedevs.com/2.2.0/location/12/",
        name: "Cape Canaveral, FL, USA",
        country_code: "USA",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_12_20200803142519.jpg",
        total_launch_count: 827,
        total_landing_count: 21,
      },
      map_image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_29_20200803143528.jpg",
      total_launch_count: 101,
    },
    webcast_live: false,
    image:
      "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/atlas2520v2520551_image_20190224012316.jpeg",
    infographic: null,
    program: [],
  },
];
