import Head from "next/head";
import styled from "styled-components";
import Countdown from "react-countdown";

import { server } from "../config";

import Layout from "../components/Layout";
import CardArticle from "../components/CardArticle";

export default function Home({ articles, launcher }) {
  console.log(articles);
  console.log(launcher, "launcher");

  return (
    <>
      <Head>
        <title>Space News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Content>
          <section>
            <header>
              <h3>
                Upcoming Launches <span>🚀</span>
              </h3>
            </header>

            {launcher.map((lanch, index) => (
              <Card key={index}>
                <div className="row">
                  <div className="col-md-auto">
                    <img src={lanch.image_url} alt="" width={100} />
                  </div>
                  <div className="col-md-8 py-3 text-center">
                    <h5>{lanch.details}</h5>
                    <h6>{lanch.launcher_config.full_name}</h6>
                    <Countdown date={Date.now() + 1000000}></Countdown>
                  </div>
                </div>
              </Card>
            ))}
          </section>
          <section>
            <header>
              <h3>
                Articles <span>📄</span>
              </h3>
            </header>
            <div className="row">
              {articles.map((art, index) => (
                <div className="col-md-6" key={index}>
                  <CardArticle art={art} />
                </div>
              ))}
            </div>
          </section>
        </Content>
      </Layout>
    </>
  );
}

const Card = styled.div`
  box-shadow: 0px 5px 10px #dfe6e9;
  width: 100%;
  margin: 2em 0;
  border-radius: 12px;
  img {
    width: 250px;
    height: 300px;
    object-fit: cover;
    border-top-left-radius: 12px;
    border-bottom-left-radius: 12px;
  }
  h5 {
    font-weight: bold;
  }
  h6 {
    color: #6c5ce7;
    font-weight: 700;
  }
`;

const Content = styled.div`
  section {
    header {
      width: 100%;
      text-align: left;
      border-bottom: 1px solid #dfe6e9;
      color: #6c5ce7;
      h3 {
        font-weight: bold;
      }
      span {
        font-weight: normal;
      }
    }
  }
`;

export const getStaticProps = async () => {
  const res = await fetch(
    "https://api.spaceflightnewsapi.net/v3/articles?_limit=5"
  );
  const response_launch = await fetch(`${server}/api/launch`);

  const articles = await res.json();
  const launcher = await response_launch.json();

  return {
    props: {
      articles,
      launcher,
    },
  };
};
